### ISSUE TITLE
Verlinkung der Meldung auf der BE-Startseite

### ISSUE THREAD

**Issue by Samson1964** [cliffparnitzky/TaskCenter#15]
Die Systemmeldung "x neue Aufgabe(n)" sollte mit dem Taskcenter verlinkt sein. Beim ersten Mal wußte ich mit der Meldung nichts anzufangen, bis ich irgendwann merkte, daß das Taskcenter gemeint war. Und meine Redakteure sind von derlei nichtssagenden Meldungen ohnehin überfordert. Deshalb wäre die Verlinkung sehr wertvoll.

**Comment by thomaspahl** [comment]
Die einzige Methode, die ich gefunden habe um das zu erreichen, ist leider eine direkte Änderung in `TaskMessages.php` function `listTasks`: dort das `return` ersetzen durch:
```
		return str_replace(array('">', '</p>'),
					array('"><a href="contao/main.php?do=tasks">', '</a></p>'),
					implode("\n", $arrReturn));
```
Funktioniert dann so wie du es dir vorstellst - und ist wirklich hilfreich. Die Taskliste ist allerdings nicht gefiltert nach dem jeweiligen Status.

**Comment by Samson1964** [comment]
Danke!
