### ISSUE TITLE
Contao 3.5.x

### ISSUE THREAD

**Issue by jgrotstabel** [cliffparnitzky/TaskCenter#16]
Hey,

wollte das Task-Center bei einem Projekt testen. Dies läuft aber bereits unter der LTS Contao 3.5. 
Ist das das Modul kompatibel? Habe nur eine Version bis Contao 3.3.4 gefunden.

Danke und viele Grüße
Jens Grotstabel

**Comment by thomaspahl** [comment]
Läuft bei mir problemlos in allen 3.5.x Versionen (bis aktuell 3.5.6) ohne Probleme und ohne Anpassungsbedarf. Siehe zusätzlich #15.
Solche Fragen aber bitte nächstens im Contao Forum stellen (ist ja keine Fehlermeldung).

Beste Grüße
Thomas

**Comment by jgrotstabel** [comment]
Ok, besten Dank.

**Comment by cliffparnitzky** [comment]
Composer sollte die Installation zulassen, was in der README steht ist ja egal (kann das aber gern anpassen).
