### ISSUE TITLE
Umstellung auf DCA

### ISSUE THREAD

**Issue by Samson1964** [cliffparnitzky/TaskCenter#17]
Ist geplant das Task-Center irgendwann auf DCA umzustellen, damit man im Backend mehr Möglichkeiten hat?

**Comment by cliffparnitzky** [comment]
Hier wurde damit begonnen: https://github.com/cliffparnitzky/TaskCenter/tree/tng

Das alles ist nun schon einige Zeit her, dass da was dran gemacht wurde. Die Nachfrage ist nicht wirklich da. Insofern sehe ich nicht, dass das weiter entwickelt wird.
